export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'
export const SET_INITIAL_INITIATIVES = 'SET_INITIAL_INITIATIVES'
export const SET_INITIATIVES = 'SET_INITIATIVES'
export const SET_INITIATIVE = 'SET_INITIATIVE'
export const SET_LAST_COMMENTS = 'SET_LAST_COMMENTS'

export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'
export const RESET_SEARCH = 'RESET_SEARCH'

export const SET_COMMENT = 'SET_COMMENT'
